# 0. project setting & shortcut
project_name: "hankyul2/FaceDA"
short_id: ''

shortcut:
  gpus: '0,'
  max_epochs: 25
  model_name: 'iresnet50'
  dropout: 0.1
  dataset_name: "MFR1"
  size:
    - 112
    - 112
  batch_size: 32
  num_workers: 4
  lr: 0.001

# 1. load dat
data:
  class_path: src.data.face.SourceOnly
  init_args:
    dataset_name: "MFR1"
    pair: "Unmasked_s5-c3"
    batch_size: 64
    num_workers: 4
    size:
      - 112
      - 112
    data_root: /home/hankyul/shared/hdd_ext/hdd4000/face/jpg
    test_data_root: /home/hankyul/shared/hdd_ext/hdd4000/face/test
    valid_ratio: 0.05
    test_pair: 'Unmasked_s5-c3'

# 2. define model (define other backbone)
model:
  class_path: src.system.face.Face_DABase
  init_args:
    backbone_init:
      model_name: "iresnet50"
      pretrained: true
#      pretrained_path: 'pretrained/DABase_IResNet/Unmasked_s1-c3_backbone.ckpt' # enable at test time
    unmasked_init:
      model_name: 'iresnet100'
      pretrained: true
      pretrained_path: 'pretrained/backbone/source_only.pth'
    verifier_init:
      model_name: 'iresnet100'
      pretrained: true
      pretrained_path: 'pretrained/backbone/verifier_backbone.pth'
    verifier_fc_init: 'pretrained/backbone/verifier_fc.pth'


# 3. prepare train tools (optimizer, learning rate scheduler)
optimizer:
  class_path: torch.optim.SGD
  init_args:
    lr: 0.001
    momentum: 0.9
    weight_decay: 0.001
    nesterov: true

lr_scheduler:
  class_path: src.lr_schedulers.PowerLR
  init_args:
    max_epochs: 0
    num_step: 0
    warmup_epoch: 0

# 4. train
seed_everything: 2021
trainer:
  # 4-1. gpu devices
  gpus: null
  accelerator: null
  amp_backend: native

  # 4-2. train setting
  max_epochs: 100
  val_check_interval: 1.0
  check_val_every_n_epoch: 1

  # 4-3. logger & callbacks
  log_every_n_steps: 50

  # 4-4. hyper param tuning
  auto_lr_find: false
  auto_scale_batch_size: false

  # 4-5. for debugging
  fast_dev_run: false
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0

  # 4-6. etc
  profiler: null
  precision: 16
  multiple_trainloader_mode: min_size
